# -*- coding: utf-8 -*-
"""MultiClass-SocialMedia-Toxicity-Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18zxkO6iwec5DNfk7vZT1H83FV2NsVJ7f
"""

import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
import re
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# 1. Memuat dataset
df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "mrmorj/hate-speech-and-offensive-language-dataset",
    "labeled_data.csv"
)

# 2. Pra-pemrosesan teks (WAJIB dijalankan terlebih dahulu agar kolom 'clean_tweet' terbentuk)
def clean_text(text):
    text = re.sub(r"http\S+|www\S+|https\S+", '', text, flags=re.MULTILINE)
    text = re.sub(r'\@\w+|\#','', text)
    text = re.sub(r'[^A-Za-z\s]', '', text)
    return text.lower().strip()

df['clean_tweet'] = df['tweet'].apply(clean_text)

# 3. Visualisasi distribusi kelas & panjang teks
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

label_names = {0: "Hate Speech", 1: "Offensive Language", 2: "Neither"}
counts = df["class"].value_counts().sort_index()
colors = ["#ef4444", "#f59e0b", "#22c55e"] # Merah, Oranye, Hijau

axes[0].bar([label_names[i] for i in counts.index], counts.values, color=colors, alpha=0.85)
for i, v in enumerate(counts.values):
    axes[0].text(i, v + 200, f"{v}\n({v/len(df):.1%})", ha="center", fontweight="bold")
axes[0].set_title("Distribusi Kelas — Sangat Imbalanced!", fontsize=12)
axes[0].set_ylabel("Jumlah Data")

df["text_len"] = df["clean_tweet"].apply(len)
for label, color in zip([0, 1, 2], colors):
    subset = df[df["class"] == label]["text_len"]
    axes[1].hist(subset, bins=30, alpha=0.6, label=label_names[label], color=color)
axes[1].set_title("Distribusi Panjang Teks per Kelas", fontsize=12)
axes[1].set_xlabel("Jumlah Karakter")
axes[1].legend()

plt.tight_layout()
plt.show()

# 4. Train/Val/Test split (Stratified 3 Kelas)
X_raw = df["clean_tweet"].values
y_raw = df["class"].values

X_train_raw, X_temp_raw, y_train, y_temp = train_test_split(
    X_raw, y_raw, test_size=0.3, random_state=42, stratify=y_raw
)
X_val_raw, X_test_raw, y_val, y_test = train_test_split(
    X_temp_raw, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

print(f"Train : {len(X_train_raw)} sampel")
print(f"Val   : {len(X_val_raw)} sampel")
print(f"Test  : {len(X_test_raw)} sampel")
print("\n✅ Proporsi kelas 0, 1, dan 2 konsisten di semua split — stratified split berhasil")



from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, confusion_matrix, classification_report)

results_summary = {}  # Menyimpan semua hasil untuk perbandingan akhir

def evaluate_model(name, y_true, y_pred, train_time=None, inference_time=None, n_params=None):
    """Evaluasi standar yang disesuaikan untuk multi-kelas (3 kategori)."""
    acc = accuracy_score(y_true, y_pred)
    # Menggunakan average='weighted' karena label memiliki jumlah data yang tidak seimbang (imbalanced)
    prec = precision_score(y_true, y_pred, average='weighted', zero_division=0)
    rec = recall_score(y_true, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_true, y_pred, average='weighted', zero_division=0)

    results_summary[name] = {
        "accuracy": acc, "precision": prec, "recall": rec, "f1": f1,
        "train_time": train_time, "inference_time": inference_time, "n_params": n_params
    }

    print(f"=== {name} ===")
    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {prec:.4f} (Weighted)")
    print(f"Recall   : {rec:.4f} (Weighted)")
    print(f"F1-Score : {f1:.4f} (Weighted)")
    if train_time: print(f"Waktu training : {train_time:.2f}s")
    if inference_time: print(f"Waktu inference: {inference_time*1000:.2f}ms")
    print()
    return results_summary[name]

print("✅ Fungsi evaluate_model() untuk multi-kelas siap dipakai di semua section berikutnya")

import time
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train_raw)
X_test_tfidf = vectorizer.transform(X_test_raw)

# ── 1. Logistic Regression ───────────────────────────────────────────────────
t0 = time.time()
lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train_tfidf, y_train)
train_time_lr = time.time() - t0

t0 = time.time()
y_pred_lr = lr_model.predict(X_test_tfidf)
inference_time_lr = (time.time() - t0) / len(X_test_raw)

evaluate_model("TF-IDF + LogReg", y_test, y_pred_lr,
                train_time_lr, inference_time_lr)

# ── 2. Multinomial Naive Bayes ───────────────────────────────────────────────
t0 = time.time()
nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)
train_time_nb = time.time() - t0

t0 = time.time()
y_pred_nb = nb_model.predict(X_test_tfidf)
inference_time_nb = (time.time() - t0) / len(X_test_raw)

evaluate_model("TF-IDF + Naive Bayes", y_test, y_pred_nb,
                train_time_nb, inference_time_nb)

# ── 3. Support Vector Machine (SVM) ──────────────────────────────────────────
t0 = time.time()
svm_model = SVC(random_state=42)
svm_model.fit(X_train_tfidf, y_train)
train_time_svm = time.time() - t0

t0 = time.time()
y_pred_svm = svm_model.predict(X_test_tfidf)
inference_time_svm = (time.time() - t0) / len(X_test_raw)

evaluate_model("TF-IDF + SVM", y_test, y_pred_svm,
                train_time_svm, inference_time_svm)

import seaborn as sns
# Pastikan prediksi untuk masing-masing model sudah dibuat
y_pred_lr = lr_model.predict(X_test_tfidf)
y_pred_nb = nb_model.predict(X_test_tfidf)
y_pred_svm = svm_model.predict(X_test_tfidf)

# Visualisasi Confusion Matrix berdampingan untuk ketiga model
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
models_ml = [
    ("Logistic Regression", y_pred_lr),
    ("Naive Bayes", y_pred_nb),
    ("SVM", y_pred_svm)
]
class_labels = ["Hate Speech", "Offensive", "Neither"]

for ax, (name, y_pred) in zip(axes, models_ml):
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt="d", ax=ax, cmap="Blues",
                xticklabels=class_labels, yticklabels=class_labels)
    ax.set_title(f"Confusion Matrix — {name}", fontsize=12)
    ax.set_xlabel("Prediksi", fontsize=10)
    ax.set_ylabel("Aktual", fontsize=10)

plt.suptitle("Perbandingan Performa Model Klasik (3 Kelas)", fontsize=14, y=1.03)
plt.tight_layout()
plt.show()

# !pip install lazypredict

# from sklearn.ensemble import RandomForestClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.svm import LinearSVC

# clf = LazyClassifier(
#     verbose=0,
#     ignore_warnings=True,
#     classifiers=[
#         LogisticRegression,
#         RandomForestClassifier,
#         LinearSVC,
#         MultinomialNB,
#     ],
# )

# models, predictions = clf.fit(
#     X_train_tfidf.toarray(), X_test_tfidf.toarray(), y_train, y_test
# )
# print(models)

"""---
## 2️⃣ Deep Learning — Multi-Layer Perceptron (MLP)

Upgrade dari ML klasik: gunakan neural network feedforward sederhana di atas fitur TF-IDF.  
Ini BUKAN sequential model (belum RNN) — hanya fully-connected layers.

> 💡 **Predict First:** MLP punya lebih banyak parameter dari Logistic Regression. Apakah otomatis lebih akurat untuk dataset yang relatif kecil dan sederhana ini?
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

tf.random.set_seed(42)
print(f"TensorFlow version: {tf.__version__}")
print(f"GPU tersedia: {len(tf.config.list_physical_devices('GPU')) > 0}")

import torch
from transformers import AutoTokenizer

# 1. Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

# 2. Buat PyTorch Dataset Custom
class TextDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        inputs = self.tokenizer(
            text,
            max_length=self.max_len,
            padding="max_length",
            truncating=True,
            return_tensors="pt"
        )
        item = {key: val.squeeze(0) for key, val in inputs.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# 3. Inisialisasi Dataset untuk Train dan Validation
train_dataset = TextDataset(X_train_raw, y_train, tokenizer)
val_dataset = TextDataset(X_val_raw, y_val, tokenizer)

# Transformasi data validasi yang sebelumnya terlewat
X_val_tfidf = vectorizer.transform(X_val_raw)

# Ubah semuanya ke dense array untuk MLP
X_train_dense = X_train_tfidf.toarray()
X_val_dense   = X_val_tfidf.toarray()
X_test_dense  = X_test_tfidf.toarray()

print(f"Shape: {X_train_dense.shape} (siap sebagai input MLP)")

def build_mlp(input_dim):
    model = keras.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(128, activation="relu"),
        layers.Dropout(0.4),
        layers.Dense(64, activation="relu"),
        layers.Dropout(0.3),
        layers.Dense(64, activation="relu"),
        layers.Dropout(0.3),
        layers.Dense(3, activation="softmax")  # Diubah ke 3 node & softmax untuk 3 kelas
    ], name="MLP_Classifier")
    return model

mlp_model = build_mlp(X_train_dense.shape[1])
mlp_model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",  # Diubah untuk label integer 3 kelas
    metrics=["accuracy"]
)
mlp_model.summary()

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_weights = compute_class_weight("balanced", classes=np.unique(y_train), y=y_train)

# Menggunakan enumerate agar otomatis mencakup seluruh kelas (0, 1, dan 2)
class_weight_dict = dict(enumerate(class_weights))
print(f"Class weights: {class_weight_dict}")

import time

t0 = time.time()
history_mlp = mlp_model.fit(
    X_train_dense,
    y_train,
    validation_data=(X_val_dense, y_val),
    epochs=30,
    batch_size=32,
    class_weight=class_weight_dict,
    callbacks=[
        keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=5, restore_best_weights=True
        )
    ],
    verbose=1,
)
train_time_mlp = time.time() - t0

print(
    f"✅ Training selesai dalam {train_time_mlp:.2f}s ({len(history_mlp.history['loss'])} epoch)"
)

import time

t0 = time.time()
y_pred_proba_mlp = mlp_model.predict(X_test_dense, verbose=0)
inference_time_mlp = (time.time() - t0) / len(X_test_raw)

# Menggunakan np.argmax untuk mengambil indeks probabilitas tertinggi dari 3 kelas
y_pred_mlp = np.argmax(y_pred_proba_mlp, axis=1)
n_params_mlp = mlp_model.count_params()

evaluate_model(
    "TF-IDF + MLP (Deep Learning)",
    y_test,
    y_pred_mlp,
    train_time_mlp,
    inference_time_mlp,
    n_params_mlp,
)

# ── 2.5 Training curve ────────────────────────────────────────────────────────
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(11, 4))
axes[0].plot(history_mlp.history["accuracy"], label="train")
axes[0].plot(history_mlp.history["val_accuracy"], label="val")
axes[0].set_title("MLP — Accuracy")
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].plot(history_mlp.history["loss"], label="train")
axes[1].plot(history_mlp.history["val_loss"], label="val")
axes[1].set_title("MLP — Loss")
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

"""---
## 3️⃣ RNN-Based Models (LSTM, GRU, BiLSTM)

Sekarang kita beralih ke model SEQUENTIAL — model membaca teks token demi token, bukan hanya melihat frekuensi kata seperti TF-IDF.

> 💡 **Predict First:** RNN-based model memahami URUTAN kata. Untuk offensive comment detection, apakah urutan kata benar-benar penting, atau cukup dengan "kata kunci" seperti TF-IDF?
"""

# ── 3.1 Tokenisasi & Padding ─────────────────────────────────────────────────
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

VOCAB_SIZE = 5000
MAX_LEN = 100  # Tweet/komentar media sosial, 100 token sudah lebih dari cukup
EMBED_DIM = 64

tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train_raw)


def encode_seq(texts):
    seqs = tokenizer.texts_to_sequences(texts)
    return pad_sequences(seqs, maxlen=MAX_LEN, padding="pre", truncating="pre")


X_train_seq = encode_seq(X_train_raw)
X_val_seq = encode_seq(X_val_raw)
X_test_seq = encode_seq(X_test_raw)

print(f"Shape sequence: {X_train_seq.shape}")
print(
    f"Vocabulary digunakan: {min(VOCAB_SIZE, len(tokenizer.word_index))} kata"
)

import numpy as np
import time


def build_rnn_model(
    rnn_type="LSTM", units=64, bidirectional=False, vocab_size=5000, embed_dim=64
):
  """Builder fleksibel untuk LSTM, GRU, atau BiLSTM (3 Kelas)."""
  inputs = keras.Input(shape=(MAX_LEN,))
  x = layers.Embedding(vocab_size, embed_dim)(inputs)

  if rnn_type == "LSTM":
    rnn_layer = layers.LSTM(units)
  elif rnn_type == "GRU":
    rnn_layer = layers.GRU(units)

  if bidirectional:
    x = layers.Bidirectional(rnn_layer)(x)
  else:
    x = rnn_layer(x)

  x = layers.Dense(32, activation="relu")(x)
  x = layers.Dropout(0.3)(x)

  # PERBAIKAN: Menambahkan (x) agar menjadi KerasTensor
  outputs = layers.Dense(3, activation="softmax")(x)

  name = f"{'Bi' if bidirectional else ''}{rnn_type}"
  return keras.Model(inputs, outputs, name=name)


def train_and_eval_rnn(model_name, rnn_type, bidirectional=False, epochs=20):
    model = build_rnn_model(
        rnn_type=rnn_type, units=64, bidirectional=bidirectional
    )
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )

    cb = [
        keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=3, restore_best_weights=True
        )
    ]

    t0 = time.time()
    # Tambahkan class_weight=class_weight_dict di sini
    history = model.fit(
        X_train_seq,
        y_train,
        validation_data=(X_val_seq, y_val),
        epochs=epochs,
        batch_size=32,
        class_weight=class_weight_dict,
        callbacks=cb,
        verbose=1,
    )
    train_time = time.time() - t0

    t0 = time.time()
    y_pred_proba = model.predict(X_test_seq, verbose=0)
    inference_time = (time.time() - t0) / len(X_test_raw)
    y_pred = np.argmax(y_pred_proba, axis=1)

    evaluate_model(
        model_name,
        y_test,
        y_pred,
        train_time,
        inference_time,
        model.count_params(),
    )
    return model, history


print("✅ Helper function siap — silakan jalankan training LSTM, GRU, BiLSTM")

# ── 3.3 Training LSTM ────────────────────────────────────────────────────────
model_lstm, history_lstm = train_and_eval_rnn("LSTM", rnn_type="LSTM")

# ── 3.4 Training GRU ─────────────────────────────────────────────────────────
model_gru, history_gru = train_and_eval_rnn("GRU", rnn_type="GRU")

# ── 3.5 Training BiLSTM ──────────────────────────────────────────────────────
model_bilstm, history_bilstm = train_and_eval_rnn("BiLSTM", rnn_type="LSTM", bidirectional=True)



# ── 3.6 Bandingkan training curve ketiga model RNN ───────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))

for hist, name, color in [(history_lstm, "LSTM", "#2563eb"),
                            (history_gru, "GRU", "#059669"),
                            (history_bilstm, "BiLSTM", "#7c3aed")
                            ]:
    axes[0].plot(hist.history["val_accuracy"], label=name, color=color)
    axes[1].plot(hist.history["val_loss"], label=name, color=color)

axes[0].set_title("Validation Accuracy"); axes[0].legend(); axes[0].grid(alpha=0.3)
axes[1].set_title("Validation Loss"); axes[1].legend(); axes[1].grid(alpha=0.3)

plt.suptitle("Perbandingan Training — LSTM vs GRU vs BiLSTM", fontsize=13)
plt.tight_layout()
plt.show()



"""---
## 4️⃣ distilledBERT (Fine-Tuned Transformer)

Pendekatan paling canggih: fine-tune model BERT pre-trained untuk task klasifikasi komentar.

BERT sudah "tahu" bahasa Inggris secara umum (dilatih di Wikipedia + BookCorpus) — kita hanya perlu mengadaptasinya (fine-tune) untuk task spesifik ini.

> 💡 **Predict First:** BERT punya ~110 juta parameter dibanding LSTM yang hanya puluhan ribu. Untuk dataset SEDERHANA seperti komentar negatif, apakah peningkatan akurasi (jika ada) sepadan dengan biaya komputasi yang jauh lebih besar?

"""

# !pip install -q transformers datasets accelerate scikit-learn

from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import torch

MODEL_NAME = "distilbert-base-uncased"
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
if device == "cpu":
    print("⚠️  Tidak ada GPU terdeteksi — training BERT akan SANGAT lambat di CPU.")
    print("   Disarankan jalankan di Google Colab dengan GPU runtime (Runtime > Change runtime type > GPU)")

bert_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
print(f"\n✅ Tokenizer loaded: {MODEL_NAME}")

# ── 4.1 & 4.2 Inisialisasi Tokenizer & Tokenisasi untuk BERT ─────────────────
from transformers import AutoTokenizer

MODEL_NAME = "distilbert-base-uncased"
bert_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_for_bert(texts, max_length=128):
    return bert_tokenizer(
        list(texts), truncation=True, padding="max_length",
        max_length=max_length, return_tensors="pt"
    )

train_encodings = tokenize_for_bert(X_train_raw)
val_encodings   = tokenize_for_bert(X_val_raw)
test_encodings  = tokenize_for_bert(X_test_raw)

print(f"Shape input_ids: {train_encodings['input_ids'].shape}")
print(f"Contoh tokenisasi:")
print(f"  Teks    : '{X_train_raw[0][:60]}...'")
print(f"  Tokens  : {bert_tokenizer.convert_ids_to_tokens(train_encodings['input_ids'][0][:15])}")

# ── 4.3 Dataset wrapper untuk PyTorch ────────────────────────────────────────
class AbusiveCommentDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = AbusiveCommentDataset(train_encodings, y_train)
val_dataset   = AbusiveCommentDataset(val_encodings, y_val)
test_dataset  = AbusiveCommentDataset(test_encodings, y_test)

print(f"✅ Dataset siap: train={len(train_dataset)}, val={len(val_dataset)}, test={len(test_dataset)}")

# ── 4.4 Load model BERT untuk klasifikasi ────────────────────────────────────
bert_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=2
).to(device)

n_params_bert = sum(p.numel() for p in bert_model.parameters())
print(f"✅ Model loaded: {MODEL_NAME}")
print(f"   Total parameter: {n_params_bert:,}")
print(f"   (Bandingkan dengan LSTM yang hanya puluhan ribu parameter!)")

# ── 4.5 Setup Trainer & class weights untuk imbalanced data ──────────────────
import torch
from torch.nn import CrossEntropyLoss
from transformers import Trainer, TrainingArguments

# Pastikan device sudah terdefinisi (biasanya cuda / cpu)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# class_weights dari perhitungan sklearn sebelumnya (untuk 3 kelas)
class_weights_tensor = torch.tensor(
    [class_weight_dict[0], class_weight_dict[1], class_weight_dict[2]],
    dtype=torch.float,
).to(device)


class WeightedTrainer(Trainer):
  """Custom Trainer dengan weighted loss untuk handle imbalanced data."""

  def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
    labels = inputs.pop("labels")
    outputs = model(**inputs)
    logits = outputs.logits
    loss_fct = CrossEntropyLoss(weight=class_weights_tensor)
    loss = loss_fct(logits, labels)
    return (loss, outputs) if return_outputs else loss


training_args = TrainingArguments(
    output_dir="./bert_results",
    num_train_epochs=3,  # BERT fine-tuning biasanya cukup 2-4 epoch
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    eval_strategy="epoch",
    save_strategy="no",  # Tidak save checkpoint untuk hemat disk di demo ini
    logging_steps=50,
    learning_rate=2e-5,  # LR kecil — standar untuk fine-tuning BERT
    report_to="none",
)

print("✅ Training configuration siap")
print(f"   Epochs: {training_args.num_train_epochs}")
print(f"   Batch size: {training_args.per_device_train_batch_size}")
print(f"   Learning rate: {training_args.learning_rate}")

import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support


def compute_metrics(eval_pred):
  logits, labels = eval_pred
  predictions = np.argmax(logits, axis=-1)

  # Menghitung metrics untuk multi-class (3 kelas)
  precision, recall, f1, _ = precision_recall_fscore_support(
      labels, predictions, average="weighted", zero_division=0
  )
  acc = accuracy_score(labels, predictions)

  return {"accuracy": acc, "f1": f1, "precision": precision, "recall": recall}



from transformers import AutoModelForSequenceClassification

# Inisialisasi ulang model BERT dengan num_labels=3
MODEL_NAME = "distilbert-base-uncased"
bert_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=3, ignore_mismatched_sizes=True
).to(device)

# Setup ulang Trainer
trainer = WeightedTrainer(
    model=bert_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

print("⏳ Training BERT... (pastikan Runtime GPU aktif di Google Colab)")
t0 = time.time()
trainer.train()
train_time_bert = time.time() - t0
print(
    f"\n✅ Training BERT selesai dalam {train_time_bert:.1f}s"
    f" ({train_time_bert/60:.1f} menit)"
)

# ── 4.7 Evaluasi BERT di test set ────────────────────────────────────────────
import time
import numpy as np

t0 = time.time()
test_predictions = trainer.predict(test_dataset)
inference_time_bert = (time.time() - t0) / len(X_test_raw)

y_pred_bert = np.argmax(test_predictions.predictions, axis=1)

# Hitung jumlah parameter model BERT
n_params_bert = sum(p.numel() for p in bert_model.parameters())

evaluate_model(
    "BERT (fine-tuned)",
    y_test,
    y_pred_bert,
    train_time_bert,
    inference_time_bert,
    n_params_bert,
)

# ── 4.8 Contoh prediksi BERT pada kalimat baru (Abusive/Hate Speech) ─────────
def predict_bert(texts):
  enc = tokenize_for_bert(texts, max_length=128)
  enc = {k: v.to(device) for k, v in enc.items()}
  bert_model.eval()
  with torch.no_grad():
    logits = bert_model(**enc).logits
  probs = torch.softmax(logits, dim=-1)
  preds = torch.argmax(probs, dim=-1)
  return preds.cpu().numpy(), probs.cpu().numpy()


# Label mapping untuk dataset 3 kelas
label_map = {0: "🚨 Hate Speech", 1: "⚠️ Offensive Language", 2: "✅ Neither"}

contoh_baru = [
    "Have a wonderful day, see you at the office tomorrow!",
    "You are so stupid and useless, get out of here!",
    "Let's go grab some coffee after work.",
]

preds, probs = predict_bert(contoh_baru)
print("=== Prediksi BERT pada Komentar Baru ===\n")
for text, pred, prob in zip(contoh_baru, preds, probs):
  label = label_map[pred]
  confidence = prob[pred]
  print(
      f"{label} ({confidence:.1%}) — \"{text[:60]}...\""
      if len(text) > 60
      else f"{label} ({confidence:.1%}) — \"{text}\""
  )



# Hitung parameter masing-masing model ML
n_params_lr = lr_model.coef_.size + lr_model.intercept_.size
n_params_nb = nb_model.feature_log_prob_.size + nb_model.class_log_prior_.size
n_params_svm = svm_model.support_vectors_.size

# 1. Logistic Regression
evaluate_model(
    "TF-IDF + LogReg",
    y_test,
    y_pred_lr,
    train_time_lr,
    inference_time_lr,
    n_params=n_params_lr,  # Pastikan n_params diisi di sini
)

# 2. Naive Bayes
evaluate_model(
    "TF-IDF + Naive Bayes",
    y_test,
    y_pred_nb,
    train_time_nb,
    inference_time_nb,
    n_params=n_params_nb,  # Pastikan n_params diisi di sini
)

# 3. Support Vector Machine (SVM)
evaluate_model(
    "TF-IDF + SVM",
    y_test,
    y_pred_svm,
    train_time_svm,
    inference_time_svm,
    n_params=n_params_svm,  # Pastikan n_params diisi di sini
)

# ── 5.1 Tabel ringkasan lengkap ──────────────────────────────────────────────
import pandas as pd

df_results = pd.DataFrame(results_summary).T
df_results = df_results[[
    "accuracy",
    "precision",
    "recall",
    "f1",
    "train_time",
    "inference_time",
    "n_params",
]]
df_results = df_results.sort_values("f1", ascending=False)

print("=== TABEL PERBANDINGAN LENGKAP ===\n")
pd.set_option(
    "display.float_format",
    lambda x: f"{x:.4f}" if abs(x) < 1000 else f"{x:,.0f}",
)

# Tampilkan tabel perbandingan secara interaktif di Colab
display(df_results)

best_model = df_results.index[0]
print(f"\n🏆 Model dengan F1-score tertinggi: {best_model}")

# ── 5.2 Visualisasi: Bar chart F1-Score semua model ──────────────────────────
plt.figure(figsize=(11, 5))
colors_map = {
    "TF-IDF + LogisticRegression": "#64748b", "TF-IDF + Naive Bayes": "#64748b", "TF-IDF + Linear SVM": "#64748b",
    "TF-IDF + MLP (Deep Learning)": "#0891b2",
    "LSTM": "#7c3aed", "GRU": "#7c3aed",# "BiLSTM": "#7c3aed",
    "BERT (fine-tuned)": "#059669",
}
colors_list = [colors_map.get(name, "#94a3b8") for name in df_results.index]

bars = plt.barh(df_results.index[::-1], df_results["f1"][::-1], color=colors_list[::-1], alpha=0.85)
for bar, val in zip(bars, df_results["f1"][::-1]):
    plt.text(bar.get_width()+0.005, bar.get_y()+bar.get_height()/2, f"{val:.3f}",
              va="center", fontsize=10, fontweight="bold")

plt.xlim(0, 1.08)
plt.xlabel("F1-Score (test set)")
plt.title("Perbandingan F1-Score — Semua Model\n(F1 dipilih karena dataset imbalanced)", fontsize=13)

from matplotlib.patches import Patch
legend = [
    Patch(color="#64748b", label="ML Klasik"),
    Patch(color="#0891b2", label="Deep Learning (MLP)"),
    Patch(color="#7c3aed", label="RNN-based"),
    Patch(color="#059669", label="BERT"),
]
plt.legend(handles=legend, loc="lower right")
plt.tight_layout()
plt.show()

# ── 5.3 Trade-off: Akurasi vs Waktu Training vs Jumlah Parameter ────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for name in df_results.index:
    row = df_results.loc[name]
    color = colors_map.get(name, "#94a3b8")

    axes[0].scatter(row["train_time"], row["f1"], s=150, c=color, alpha=0.85,
                     edgecolors="white", linewidth=1.5, zorder=5)
    axes[0].annotate(name, (row["train_time"], row["f1"]),
                       textcoords="offset points", xytext=(6, 4), fontsize=8)

    axes[1].scatter(row["n_params"], row["f1"], s=150, c=color, alpha=0.85,
                     edgecolors="white", linewidth=1.5, zorder=5)
    axes[1].annotate(name, (row["n_params"], row["f1"]),
                       textcoords="offset points", xytext=(6, 4), fontsize=8)

axes[0].set_xlabel("Waktu Training (detik)"); axes[0].set_ylabel("F1-Score")
axes[0].set_title("F1-Score vs Waktu Training", fontsize=12)
axes[0].grid(alpha=0.3)

axes[1].set_xscale("log")
axes[1].set_xlabel("Jumlah Parameter (log scale)"); axes[1].set_ylabel("F1-Score")
axes[1].set_title("F1-Score vs Kompleksitas Model", fontsize=12)
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

print("💡 Titik kiri-atas (waktu/parameter rendah, F1 tinggi) = paling efisien.")
print("   Apakah model paling kompleks (BERT) selalu memberikan ROI terbaik")
print("   untuk dataset komentar seperti ini?")

# ── 5.4 Confusion Matrix model terbaik vs model paling sederhana ─────────────
# Mengambil nama model dengan n_params terkecil
simplest_model_name = df_results["n_params"].astype(float).idxmin()

# PERBAIKAN: Nama key disesuaikan persis dengan yang ada di df_results
pred_map = {
    "TF-IDF + LogReg": y_pred_lr,
    "TF-IDF + Naive Bayes": y_pred_nb,
    "TF-IDF + SVM": y_pred_svm,
    "TF-IDF + MLP (Deep Learning)": y_pred_mlp,
    "LSTM": np.argmax(model_lstm.predict(X_test_seq, verbose=0), axis=1),
    "GRU": np.argmax(model_gru.predict(X_test_seq, verbose=0), axis=1),
    # "BiLSTM": np.argmax(model_bilstm.predict(X_test_seq, verbose=0), axis=1),
    "BERT (fine-tuned)": y_pred_bert,
}

# Label kelas sesuai dataset (3 kelas)
class_labels = ["Hate Speech", "Offensive", "Neither"]

fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))

# 1. Confusion Matrix Model Terbaik
cm_best = confusion_matrix(y_test, pred_map[best_model])
sns.heatmap(
    cm_best,
    annot=True,
    fmt="d",
    ax=axes[0],
    cmap="Greens",
    xticklabels=class_labels,
    yticklabels=class_labels,
)
axes[0].set_title(f"Terbaik (F1): {best_model}", fontsize=11)
axes[0].set_xlabel("Prediksi")
axes[0].set_ylabel("Aktual")

# 2. Confusion Matrix Model Paling Sederhana
cm_simple = confusion_matrix(y_test, pred_map[simplest_model_name])
sns.heatmap(
    cm_simple,
    annot=True,
    fmt="d",
    ax=axes[1],
    cmap="Blues",
    xticklabels=class_labels,
    yticklabels=class_labels,
)
axes[1].set_title(f"Paling sederhana: {simplest_model_name}", fontsize=11)
axes[1].set_xlabel("Prediksi")
axes[1].set_ylabel("Aktual")

plt.tight_layout()
plt.show()

# ── 5.5 Tabel keputusan: kapan pakai model apa? ──────────────────────────────
import pandas as pd

decision_table = pd.DataFrame([
    ["ML Klasik (TF-IDF+LogReg)", "Prototipe cepat, dataset kecil-menengah, perlu interpretability, resource terbatas"],
    ["Deep Learning (MLP)",        "Dataset cukup besar, butuh sedikit lebih fleksibel dari linear model"],
    ["RNN (LSTM/GRU/BiLSTM)",      "Urutan kata penting, dataset menengah-besar, ada GPU untuk training"],
    ["BERT (fine-tuned)",          "Butuh akurasi maksimal, dataset kompleks/ambigu, ada GPU, latency bukan masalah kritis"],
], columns=["Pendekatan", "Kapan Sebaiknya Dipakai"])

print(decision_table.to_string(index=False))

print("\n📌 Untuk dataset Abusive Comment / Hate Speech ini (di mana konteks dan")
print("   struktur kalimat penting untuk membedakan hate speech, offensive, atau neither),")
print("   model berbasis Transformer seperti BERT memberikan pemahaman yang jauh")
print("   lebih baik terhadap nuansa bahasa sosial media yang kompleks.")

# ── 6.1 Temukan kasus yang diprediksi berbeda oleh model ──────────────────────
# Mapping angka ke nama label 3 kelas
label_map = {0: "Hate Speech", 1: "Offensive", 2: "Neither"}

df_test_analysis = pd.DataFrame({
    "text": X_test_raw,
    "true_label": y_test,
    "pred_logreg": y_pred_lr,
    "pred_bert": y_pred_bert,
})

# Kasus di mana LogReg dan BERT BERBEDA prediksi
disagree = df_test_analysis[
    df_test_analysis["pred_logreg"] != df_test_analysis["pred_bert"]
]
print(f"Jumlah kasus di mana LogReg dan BERT BERBEDA prediksi: {len(disagree)}")

if len(disagree) > 0:
  print("\n=== Contoh kasus yang diprediksi berbeda ===\n")
  for _, row in disagree.head(5).iterrows():
    true_lbl = label_map[row["true_label"]]
    lr_lbl = label_map[row["pred_logreg"]]
    bert_lbl = label_map[row["pred_bert"]]

    print(f"Teks      : {row['text'][:80]}")
    print(f"Label asli: {true_lbl}")
    print(f"LogReg    : {lr_lbl} {'✅' if lr_lbl == true_lbl else '❌'}")
    print(f"BERT      : {bert_lbl} {'✅' if bert_lbl == true_lbl else '❌'}")
    print("-" * 50)

import joblib

# Simpan model Logistic Regression dan TfidfVectorizer
joblib.dump(lr_model, "logistic_regression_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print(
    "✅ Model Logistic Regression & Vectorizer berhasil disimpan secara lokal di"
    " Colab!"
)

import shutil
from google.colab import files
from transformers import AutoTokenizer

# 1. Tentukan direktori penyimpanan
bert_save_path = "./saved_bert_model"

# 2. Simpan model dari Trainer
trainer.save_model(bert_save_path)

# 3. Load & Simpan tokenizer BERT Hugging Face (bukan Keras tokenizer)
# Sesuaikan 'bert-base-uncased' dengan nama model pretrained BERT yang Anda gunakan
bert_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
bert_tokenizer.save_pretrained(bert_save_path)

print(
    f"✅ Model BERT & Tokenizer berhasil disimpan di direktori {bert_save_path}!"
)

# 4. Kompres ke ZIP dan unduh secara otomatis
shutil.make_archive("saved_bert_model", "zip", bert_save_path)
files.download("saved_bert_model.zip")



"""Testing Model


"""

# !pip install pyngrok streamlit

import os
import re
import pickle
from pyngrok import ngrok
from google.colab import userdata

# 1. Simpan Model Logistic Regression & TF-IDF Vectorizer
with open('lr_model.pkl', 'wb') as f:
    pickle.dump(lr_model, f)

with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

# 2. Buat file app.py (Raw String r"..." digunakan untuk mencegah SyntaxWarning \S)
app_code = r"""
import os
import re
import pickle
import torch
import streamlit as st
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Konfigurasi Halaman Streamlit
st.set_page_config(
    page_title="Abusive Comment Classifier",
    page_icon="💬",
    layout="centered"
)

# --- 1. Load Model TF-IDF ---
@st.cache_resource
def load_tfidf_assets():
    with open('lr_model.pkl', 'rb') as f:
        model = pickle.load(f)
    with open('vectorizer.pkl', 'rb') as f:
        vectorizer = pickle.load(f)
    return model, vectorizer

lr_model, vectorizer = load_tfidf_assets()

# --- 2. Load Model Fine-Tuned DistilBERT ---
@st.cache_resource
def load_bert_assets():
    model_path = './saved_bert_model'
    if os.path.exists(model_path):
        tokenizer = AutoTokenizer.from_pretrained(model_path)
        model = AutoModelForSequenceClassification.from_pretrained(model_path)
    else:
        tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
        model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=3)

    model.eval()
    return tokenizer, model

try:
    bert_tokenizer, bert_model = load_bert_assets()
    bert_ready = True
except Exception:
    bert_ready = False

# Preprocessing Teks
def clean_text(text):
    text = re.sub(r"http\S+|www\S+|https\S+", '', text, flags=re.MULTILINE)
    text = re.sub(r'\@\w+|\#', '', text)
    text = re.sub(r'[^A-Za-z\s]', '', text)
    return text.lower().strip()

label_map = {0: "Hate Speech", 1: "Offensive Language", 2: "Neither"}

# Interface Utama
st.title("💬 Abusive Comment Classifier")
st.write("Uji coba dan bandingkan hasil klasifikasi komentar menggunakan berbagai arsitektur model.")

tab1, tab2 = st.tabs(["📊 TF-IDF + Logistic Regression", "🤖 Fine-Tuned DistilBERT"])

# ---------------- TAB 1: TF-IDF ----------------
with tab1:
    st.subheader("Model TF-IDF + Logistic Regression")
    user_input_tfidf = st.text_area("Masukkan Komentar:", placeholder="Contoh: You are so stupid...", key="tfidf_input")

    if st.button("Klasifikasikan (TF-IDF)", type="primary", key="btn_tfidf"):
        if not user_input_tfidf.strip():
            st.warning("⚠️ Silakan masukkan teks komentar terlebih dahulu!")
        else:
            cleaned_input = clean_text(user_input_tfidf)
            input_tfidf = vectorizer.transform([cleaned_input])

            prediction = lr_model.predict(input_tfidf)[0]
            probabilities = lr_model.predict_proba(input_tfidf)[0]

            result_label = label_map[prediction]

            st.markdown("### Hasil Klasifikasi:")
            if prediction == 0:
                st.error(f"🚨 **{result_label}**")
            elif prediction == 1:
                st.warning(f"⚠️ **{result_label}**")
            else:
                st.success(f"✅ **{result_label}**")

            st.markdown("---")
            st.write("**Probabilitas Setiap Kelas:**")
            col1, col2, col3 = st.columns(3)
            col1.metric("Hate Speech", f"{probabilities[0]*100:.1f}%")
            col2.metric("Offensive", f"{probabilities[1]*100:.1f}%")
            col3.metric("Neither", f"{probabilities[2]*100:.1f}%")

# ---------------- TAB 2: DISTILBERT ----------------
with tab2:
    st.subheader("Model Fine-Tuned DistilBERT")
    user_input_bert = st.text_area("Masukkan Komentar:", placeholder="Contoh: You are so stupid...", key="bert_input")

    if st.button("Klasifikasikan (BERT)", type="primary", key="btn_bert"):
        if not user_input_bert.strip():
            st.warning("⚠️ Silakan masukkan teks komentar terlebih dahulu!")
        elif not bert_ready:
            st.error("Model DistilBERT gagal dimuat.")
        else:
            cleaned_input = clean_text(user_input_bert)
            inputs = bert_tokenizer(cleaned_input, return_tensors="pt", truncation=True, padding=True, max_length=128)

            with torch.no_grad():
                outputs = bert_model(**inputs)
                probs = torch.softmax(outputs.logits, dim=1).squeeze().tolist()
                prediction = torch.argmax(outputs.logits, dim=1).item()

            result_label = label_map[prediction]

            st.markdown("### Hasil Klasifikasi (BERT):")
            if prediction == 0:
                st.error(f"🚨 **{result_label}**")
            elif prediction == 1:
                st.warning(f"⚠️ **{result_label}**")
            else:
                st.success(f"✅ **{result_label}**")

            st.markdown("---")
            st.write("**Probabilitas Setiap Kelas:**")
            col1, col2, col3 = st.columns(3)
            col1.metric("Hate Speech", f"{probs[0]*100:.1f}%")
            col2.metric("Offensive", f"{probs[1]*100:.1f}%")
            col3.metric("Neither", f"{probs[2]*100:.1f}%")
"""

with open('app.py', 'w') as f:
    f.write(app_code)

# 3. Kunci Utama: Matikan semua tunnel Ngrok & proses Streamlit terdahulu
ngrok.kill()
get_ipython().system("pkill -9 streamlit")

# 4. Set Authtoken & Buka Tunnel Baru
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

get_ipython().system("streamlit run app.py &>/dev/null &")

public_url = ngrok.connect(8501)
print(f"🚀 Streamlit Berhasil Live! Klik URL: {public_url}")